# Generated by Django 4.2.11 on 2025-03-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_host_update_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='wildcard',
            field=models.BooleanField(default=False, help_text='Register wildcard to DNS; e.g., *.name.domain', verbose_name='wildcard'),
        ),
    ]
