# Generated by Django 4.2.11 on 2025-12-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_host_wildcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ssl_certificate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
