# Generated by Django 4.2.27 on 2026-02-13 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_host_csr_host_ssl_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Virtual Organization name', max_length=255, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='VOMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.virtualorganization')),
            ],
        ),
        migrations.AddField(
            model_name='virtualorganization',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Users who belong to this Virtual Organization', related_name='vos', through='main.VOMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domain',
            name='vo',
            field=models.ForeignKey(blank=True, help_text="Limit domain to a selected virtual organization's scope.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='main.virtualorganization', verbose_name='Virtual organization'),
        ),
        migrations.AddConstraint(
            model_name='vomembership',
            constraint=models.UniqueConstraint(fields=('user', 'vo'), name='unique_user_vo_membership'),
        ),
    ]
