# Generated by Django 4.2.27 on 2026-02-19 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_virtualorganization_vomembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualorganization',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_vos', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
    ]
