# Generated by Django 4.2.27 on 2026-10-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_virtualorganization_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='certificates_enabled',
            field=models.BooleanField(default=False, help_text='Check to allow issuing SSL certificates for all hosts of this domain - if not checked, each host needs an individual approval', verbose_name='enable certificates'),
        ),
        migrations.AddField(
            model_name='host',
            name='certificates_approved',
            field=models.BooleanField(default=False, help_text='Checked if staff approved issuing SSL certificates for this host', verbose_name='certificates approved'),
        ),
        migrations.AddField(
            model_name='host',
            name='certificates_requested',
            field=models.BooleanField(default=False, help_text='Request permission to issue SSL certificates for this host - a staff member must approve it (not needed if the domain already allows certificates)', verbose_name='certificates requested'),
        ),
    ]
