# Generated by Django 4.2.11 on 2025-12-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('de', 'German'), ('el', 'Greek'), ('fr', 'French'), ('it', 'Italian'), ('es', 'Spanish'), ('pl', 'Polish')], default='', max_length=10, null=True, verbose_name='language'),
        ),
    ]
